const STORAGE_KEY='board.project.v1';
const state={projectName:'Novo projeto',slides:[{id:crypto.randomUUID(),name:'Página 1',items:[]}],active:0,selected:null,tool:'select'};
const $=s=>document.querySelector(s);const stage=$('#stage'),slidesList=$('#slidesList'),emptyHint=$('#emptyHint'),saveStatus=$('#saveStatus'),projectName=$('#projectName');
let deferredPrompt=null;
function load(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(saved&&Array.isArray(saved.slides)){Object.assign(state,saved);state.selected=null}}catch{}projectName.value=state.projectName||'Novo projeto';render()}
function save(){state.projectName=projectName.value.trim()||'Novo projeto';localStorage.setItem(STORAGE_KEY,JSON.stringify({projectName:state.projectName,slides:state.slides,active:state.active}));saveStatus.textContent='Salvo localmente';}
function current(){return state.slides[state.active]}
function render(){stage.innerHTML='';for(const item of current().items){const el=document.createElement('div');el.className=`board-item ${item.type}${state.selected===item.id?' selected':''}`;el.dataset.id=item.id;el.style.left=item.x+'px';el.style.top=item.y+'px';el.textContent=item.text;el.tabIndex=0;makeDraggable(el,item);el.ondblclick=()=>editItem(item);el.onclick=e=>{e.stopPropagation();state.selected=item.id;render()};stage.appendChild(el)}emptyHint.hidden=current().items.length>0;slidesList.innerHTML='';state.slides.forEach((slide,i)=>{const b=document.createElement('div');b.className='slide-thumb'+(i===state.active?' active':'');b.innerHTML=`<strong>${escapeHtml(slide.name)}</strong><small>${slide.items.length} elementos</small>`;b.onclick=()=>{state.active=i;state.selected=null;render();save()};slidesList.appendChild(b)});}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function addItem(type,x=220,y=160){const labels={text:'Duplo clique para editar',note:'Ideia / insight',rect:'Bloco estratégico',arrow:'→'};current().items.push({id:crypto.randomUUID(),type,text:labels[type]||'Novo item',x,y});state.selected=current().items.at(-1).id;render();save()}
function editItem(item){if(item.type==='arrow')return;const next=prompt('Editar conteúdo:',item.text);if(next!==null){item.text=next.trim()||item.text;render();save()}}
function makeDraggable(el,item){let drag=null;el.onpointerdown=e=>{if(state.tool!=='select')return;el.setPointerCapture(e.pointerId);drag={dx:e.clientX-item.x,dy:e.clientY-item.y};state.selected=item.id};el.onpointermove=e=>{if(!drag)return;item.x=Math.max(0,e.clientX-drag.dx);item.y=Math.max(0,e.clientY-drag.dy);el.style.left=item.x+'px';el.style.top=item.y+'px'};el.onpointerup=()=>{if(drag){drag=null;save();render()}}}
function deleteSelected(){if(!state.selected)return;current().items=current().items.filter(i=>i.id!==state.selected);state.selected=null;render();save()}
document.querySelectorAll('[data-tool]').forEach(btn=>btn.onclick=()=>{state.tool=btn.dataset.tool;document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b===btn));if(state.tool!=='select'){addItem(state.tool);state.tool='select';document.querySelector('[data-tool="select"]').classList.add('active');btn.classList.remove('active')}});
stage.onclick=e=>{state.selected=null;if(state.tool!=='select'){const r=stage.getBoundingClientRect();addItem(state.tool,e.clientX-r.left,e.clientY-r.top)}else render()};
$('#deleteBtn').onclick=deleteSelected;document.addEventListener('keydown',e=>{if((e.key==='Delete'||e.key==='Backspace')&&document.activeElement!==projectName)deleteSelected();if(e.key==='Escape'&&document.body.classList.contains('presenting'))togglePresent()});
$('#addSlideBtn').onclick=()=>{state.slides.push({id:crypto.randomUUID(),name:`Página ${state.slides.length+1}`,items:[]});state.active=state.slides.length-1;state.selected=null;render();save()};
function togglePresent(){document.body.classList.toggle('presenting');$('#presentBtn').textContent=document.body.classList.contains('presenting')?'Sair':'Apresentar'}$('#presentBtn').onclick=togglePresent;
projectName.oninput=()=>{saveStatus.textContent='Salvando…';clearTimeout(projectName._t);projectName._t=setTimeout(save,250)};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').hidden=true};window.addEventListener('appinstalled',()=>{$('#installBtn').hidden=true});
function updateNetwork(){const online=navigator.onLine;$('#offlineStatus').textContent=online?'Online':'Offline';$('#offlineStatus').title=online?'Conectado':'Modo offline: projeto local disponível'}window.addEventListener('online',updateNetwork);window.addEventListener('offline',updateNetwork);updateNetwork();load();
